// FOR API

export const USER: USER = 'user'
export const PRODUCT: PRODUCT = 'product'
export const PRODUCTTYPE: PRODUCTTYPE = 'product-type'
export const ATTRIBUTE: ATTRIBUTE = 'attribute'
export const CATEGORY: CATEGORY = 'category'
export const COLLECTION: COLLECTION = 'collection'
export const VARIANT: VARIANT = 'variant'
export const ORDER: ORDER = 'order'
export const VOUCHER: VOUCHER = 'voucher'
export const SALEDISCOUNT: SALEDISCOUNT = 'sale-discount'
export const GIFTCARD: GIFTCARD = 'gift-card'
export const CHECKOUT: CHECKOUT = 'checkout'
export const SHIPPINGRATE: SHIPPINGRATE = 'shipping-rate'
export const SHOP: SHOP = 'shop'
export const TAX: TAX = 'tax'
export const WEBHOOK: WEBHOOK = 'webhook'

// FOR DB

export const DBVERSION: DBVERSION = 'v1'
export const DBNAME: DBNAME = 'db'
export const USERS: USERS = 'users'
export const ADDRESSES: ADDRESSES = 'addresses'
export const SHOPS: SHOPS = 'shops'
export const CATALOG: CATALOG = 'catalog'
export const PRODUCTS: PRODUCTS = 'products'
export const VARIANTS: VARIANTS = 'variants'
export const CATEGORIES: CATEGORIES = 'categories'
export const COLLECTIONS: COLLECTIONS = 'collections'
export const PRODUCTTYPES: PRODUCTTYPES = 'productTypes'
export const ATTRIBUTES: ATTRIBUTES = 'attributes'
export const ATTRIBUTEVALUES: ATTRIBUTEVALUES = 'attributeValues'
export const ORDERS: ORDERS = 'orders'
export const TAXES: TAXES = 'taxes'
export const SALEDISCOUNTS: SALEDISCOUNTS = 'saleDiscounts'
export const VOUCHERS: VOUCHERS = 'vouchers'
export const GIFTCARDS: GIFTCARDS = 'giftCards'
export const SHIPPING: SHIPPING = 'shipping'
export const SHIPPINGRATES: SHIPPINGRATES = 'shippingRates'
export const WAREHOUSE: WAREHOUSE = 'warehouse'
export const INVENTORY: INVENTORY = 'inventory'
export const ADVERTS: ADVERTS = 'adverts'
export const PAGES: PAGES = 'pages'
export const NAVIGATION: NAVIGATION = 'navigation'
export const SUPPORT: SUPPORT = 'support'
export const ANALYTICS: ANALYTICS = 'analytics'


// FOR API

type USER = 'user'
type PRODUCT = 'product'
type PRODUCTTYPE = 'product-type'
type ATTRIBUTE = 'attribute'
type CATEGORY = 'category'
type COLLECTION = 'collection'
type VARIANT = 'variant'
type ORDER = 'order'
type VOUCHER = 'voucher'
type SALEDISCOUNT = 'sale-discount'
type GIFTCARD = 'gift-card'
type CHECKOUT = 'checkout'
type SHIPPINGRATE = 'shipping-rate'
type SHOP = 'shop'
type TAX = 'tax'
type WEBHOOK = 'webhook'

// FOR DB

type DBVERSION = 'v1'
type DBNAME = 'db'
type USERS = 'users'
type ADDRESSES = 'addresses'
type SHOPS = 'shops'
type CATALOG = 'catalog'
type PRODUCTS = 'products'
type VARIANTS = 'variants'
type CATEGORIES = 'categories'
type COLLECTIONS = 'collections'
type PRODUCTTYPES = 'productTypes'
type ATTRIBUTES = 'attributes'
type ATTRIBUTEVALUES = 'attributeValues'
type ORDERS = 'orders'
type TAXES = 'taxes'
type SALEDISCOUNTS = 'saleDiscounts'
type VOUCHERS = 'vouchers'
type GIFTCARDS = 'giftCards'
type SHIPPING = 'shipping'
type SHIPPINGRATES = 'shippingRates'
type WAREHOUSE = 'warehouse'
type INVENTORY = 'inventory'
type ADVERTS = 'adverts'
type PAGES = 'pages'
type NAVIGATION = 'navigation'
type SUPPORT = 'support'
type ANALYTICS = 'analytics'